#deployment.yaml
#namespace: devops
replicaCount: 2
image:
  repository: 113889329641.dkr.ecr.us-east-1.amazonaws.com/my_pvt_repo
  tag: latest
containerPort: 80
# service.yaml
service:
  port: 80
  targetPort: 80
  containerPort: 80
  nodePort: 30008
  type: ClusterIP
